language: python
python:
    - "3.3"
    - "3.4"

addons:
  postgresql: "9.4"

# Deactivate the automic download of submodules
git:
  submodules: false

# Deactivate the notifiations by mail
notifications:
    email: false

before_script:
  - psql -c 'CREATE DATABASE vbtournaments;' -U postgres
  - python manage.py migrate

# command to install dependencies
install:
    - pip install -r requirements.txt

# command to run tests
script: py.test